/**
 * SLIDE TITLES
 *
 * Auto-generated by extract_pdf.py
 * Define titles for each slide in your presentation
 * This is used by the sidebar navigation
 *
 * You can manually edit these titles after generation if needed.
 */

export const SLIDE_TITLES = [
  { page: 1, title: 'Geothermal Energy' },
  { page: 2, title: 'Datacenter Buildout' },
  { page: 3, title: 'The opportunity for geothermal GW-Scale capacity' },
  { page: 4, title: 'Proportionate Size' },
  { page: 5, title: 'Geothermal Capacity Addition: $100M Investment Scenario' },
  { page: 6, title: 'Geothermal Capacity Addition: $400M Investment Scenario' },
  { page: 7, title: 'Geothermal Capacity Addition: $1.6B Investment Scenario' },
  { page: 8, title: 'Geothermal Capacity Addition: $6.4B Investment Scenario' },
  { page: 9, title: '2500' },
  { page: 10, title: 'Our collective effort is a humanity-scale opportunity' },
  { page: 11, title: 'Project' },
  { page: 12, title: 'Appendix' },
  { page: 13, title: 'Geothermal   Energy' },
  { page: 14, title: 'Appendix: What are the types of next-gen geothermal systems?' },
  { page: 15, title: 'Appendix: Can geothermal be used for data center cooling?' },
  { page: 16, title: 'Shale cut costs through standardization, data, scale, and rapid innovation.' },
  { page: 17, title: 'Appendix: How can O&G expertise cut geothermal costs?' },
  { page: 18, title: 'Appendix: What cost reductions has O&G seen?' },
  { page: 19, title: 'Oman’s Trajectory of Innovation' },
  { page: 20, title: 'Growth   Potential' },
  { page: 21, title: '$100 M    11 Gw' },
  { page: 22, title: 'Agnostic       Leadership                           Bridge' },
  { page: 23, title: 'Appendix: Where in the world is geothermal?' },
  { page: 24, title: 'Appendix: Why is derisking an impactful unlock?' },
  { page: 25, title: 'Appendix: What is the proposed workflow?' },
  { page: 26, title: 'Appendix: How does catalytic capital accelerate de-risking?' },
  { page: 27, title: 'Exploration boosts success rates and compounds capacity unlocked per site.' },
  { page: 28, title: 'Appendix: Why is the gas-turbine supply chain constrained?' },
  { page: 29, title: 'Appendix: Why is the ORC supply chain more scalable?' },
  { page: 30, title: 'Appendix: How is gas-turbine supply modeled and limited?' },
  { page: 31, title: 'Appendix: What constrains other large-scale energy sources?' },
  { page: 32, title: 'Appendix: What would unlock the O&G industry?' },
  { page: 33, title: 'The Geothermal' },
  { page: 34, title: 'Region Resources Expertise Activity Center Assessment' },
  { page: 35, title: 'Geothermal Development Opportunity By Region in GW of Developable Potential' },
  { page: 36, title: 'Geothermal Development Opportunity By Region in GW of Developable Potential' },
  { page: 37, title: 'Geothermal Development Opportunity By Region in GW of Developable Potential' },
  { page: 38, title: 'Geothermal Development Opportunity By Region in GW of Developable Potential' },
  { page: 39, title: 'Geothermal Development Opportunity By Region in GW of Developable Potential' },
  { page: 40, title: 'Geothermal Development Opportunity By Region in GW of Developable Potential' },
  { page: 41, title: 'References:' },
];
