#!/usr/bin/env python3
"""
Extract PDF content with slide numbers preserved for RAG ingestion.
Uses pdfplumber for robust text extraction with layout preservation.

This script extracts text and tables from PDF presentations, formatting them
in a way that's optimized for RAG (Retrieval-Augmented Generation) systems
and AI voice assistants.

Additionally, it auto-generates the slide-titles.js file needed by the
presentation viewer's slide navigation sidebar.
"""

import pdfplumber
import sys
import os
import re
import json


def extract_slide_title(text):
    """
    Extract a slide title from page text using heuristics.

    Args:
        text: Raw text from a PDF page

    Returns:
        str: Extracted title or fallback text
    """
    if not text:
        return "Untitled Slide"

    lines = text.strip().split('\n')

    # Remove empty lines
    lines = [line.strip() for line in lines if line.strip()]

    if not lines:
        return "Untitled Slide"

    # Strategy 1: Look for lines that are all caps (common for titles)
    for line in lines[:5]:  # Check first 5 lines
        if len(line) > 3 and line.isupper() and len(line) < 100:
            return line.title()  # Convert to title case for readability

    # Strategy 2: Take the first substantial line
    for line in lines[:5]:
        # Skip page numbers, footers, etc.
        if len(line) > 5 and len(line) < 100 and not line.isdigit():
            # Clean up common artifacts
            cleaned = re.sub(r'^\d+[\.\)]\s*', '', line)  # Remove "1. " or "1) "
            cleaned = re.sub(r'\s+', ' ', cleaned)  # Normalize whitespace
            return cleaned

    # Fallback: use first line
    return lines[0][:80]  # Truncate if too long


def generate_slide_titles_js(slide_titles, output_path):
    """
    Generate the slide-titles.js file for the presentation viewer.

    Args:
        slide_titles: List of dicts with 'page' and 'title' keys
        output_path: Path to write the slide-titles.js file
    """
    js_content = '''/**
 * SLIDE TITLES
 *
 * Auto-generated by extract_pdf.py
 * Define titles for each slide in your presentation
 * This is used by the sidebar navigation
 *
 * You can manually edit these titles after generation if needed.
 */

export const SLIDE_TITLES = [
'''

    for slide in slide_titles:
        # Escape single quotes in titles
        title = slide['title'].replace("'", "\\'")
        js_content += f"  {{ page: {slide['page']}, title: '{title}' }},\n"

    js_content += '];\n'

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(js_content)


def extract_pdf_for_rag(pdf_path, output_path, presentation_title=None, generate_js_titles=True):
    """
    Extract PDF content preserving slide numbers and structure.

    Args:
        pdf_path: Path to input PDF file
        output_path: Path to output text file
        presentation_title: Optional title for the presentation (extracted from filename if not provided)
        generate_js_titles: Whether to auto-generate slide-titles.js file (default: True)
    """
    # Extract title from filename if not provided
    if presentation_title is None:
        presentation_title = os.path.splitext(os.path.basename(pdf_path))[0].replace('_', ' ').title()

    # Store slide titles for JS generation
    slide_titles = []

    with pdfplumber.open(pdf_path) as pdf:
        total_pages = len(pdf.pages)
        print(f"\n{'='*80}")
        print(f"📄 PDF EXTRACTION STARTED")
        print(f"{'='*80}")
        print(f"Input PDF: {pdf_path}")
        print(f"Total pages: {total_pages}")
        print(f"Processing...")

        with open(output_path, 'w', encoding='utf-8') as out:
            # Write header
            out.write("=" * 80 + "\n")
            out.write(f"{presentation_title}\n")
            out.write("Extracted for RAG Processing\n")
            out.write("=" * 80 + "\n\n")

            for i, page in enumerate(pdf.pages, start=1):
                # Extract text with layout preservation
                text = page.extract_text(layout=True)

                # Extract title for this slide
                slide_title = extract_slide_title(text)
                slide_titles.append({'page': i, 'title': slide_title})

                # Show progress with extracted title
                print(f"  [{i}/{total_pages}] {slide_title[:60]}{'...' if len(slide_title) > 60 else ''}")

                if text:
                    # Write page header with clear slide number
                    out.write("\n" + "=" * 80 + "\n")
                    out.write(f"SLIDE {i} (Page {i} of {total_pages})\n")
                    out.write("=" * 80 + "\n\n")

                    # Write the extracted text
                    out.write(text)
                    out.write("\n\n")

                    # Also try to extract tables if present
                    tables = page.extract_tables()
                    if tables:
                        out.write("\n--- TABLES ON THIS SLIDE ---\n\n")
                        for table_idx, table in enumerate(tables, start=1):
                            out.write(f"Table {table_idx}:\n")
                            for row in table:
                                # Filter out None values and join with | separator
                                clean_row = [str(cell) if cell else "" for cell in row]
                                out.write(" | ".join(clean_row) + "\n")
                            out.write("\n")

                else:
                    # Even if no text, mark the page
                    out.write("\n" + "=" * 80 + "\n")
                    out.write(f"SLIDE {i} (Page {i} of {total_pages})\n")
                    out.write("=" * 80 + "\n")
                    out.write("[Image-only slide or no extractable text]\n\n")

    # Generate slide-titles.js if requested
    js_output_path = None
    if generate_js_titles:
        # Determine output path for slide-titles.js
        # If extract_pdf.py is in presentation_viewer/, put it in modules/
        # Otherwise, put it next to the script
        script_dir = os.path.dirname(os.path.abspath(__file__))

        # Check if we're in the presentation_viewer directory
        if os.path.basename(script_dir) == 'presentation_viewer':
            modules_dir = os.path.join(script_dir, 'modules')
            if os.path.exists(modules_dir):
                js_output_path = os.path.join(modules_dir, 'slide-titles.js')
            else:
                js_output_path = os.path.join(script_dir, 'slide-titles.js')
        else:
            # Put it in the same directory as the output file
            js_output_path = os.path.join(os.path.dirname(output_path), 'slide-titles.js')

        generate_slide_titles_js(slide_titles, js_output_path)

    # Print summary
    print(f"\n{'='*80}")
    print(f"✅ EXTRACTION COMPLETE")
    print(f"{'='*80}")
    print(f"\n📝 RAG Content File:")
    print(f"   {output_path}")
    print(f"   → {total_pages} slides extracted")
    print(f"   → Ready for ElevenLabs agent ingestion")

    if generate_js_titles and js_output_path:
        print(f"\n🗂️  Slide Navigation File:")
        print(f"   {js_output_path}")
        print(f"   → {len(slide_titles)} slide titles generated")
        print(f"   → Ready for presentation viewer sidebar")
        print(f"   → You can manually edit titles if needed")

    print(f"\n{'='*80}\n")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("\n" + "="*80)
        print("PDF Extraction for Presentation Viewer")
        print("="*80)
        print("\nUsage: python extract_pdf.py <pdf_file> [output_file] [presentation_title]")
        print("\nOptions:")
        print("  --no-js-titles    Skip auto-generation of slide-titles.js")
        print("\nExamples:")
        print("  python extract_pdf.py presentation.pdf")
        print("  python extract_pdf.py presentation.pdf output.txt")
        print("  python extract_pdf.py presentation.pdf output.txt 'My Presentation Title'")
        print("  python extract_pdf.py presentation.pdf --no-js-titles")
        print("\n" + "="*80 + "\n")
        sys.exit(1)

    # Parse arguments
    args = [arg for arg in sys.argv[1:] if not arg.startswith('--')]
    flags = [arg for arg in sys.argv[1:] if arg.startswith('--')]

    if len(args) < 1:
        print("\n❌ Error: Please provide a PDF file\n")
        print("Run without arguments to see usage examples\n")
        sys.exit(1)

    pdf_file = args[0]

    # Default output filename based on input
    default_output = os.path.splitext(pdf_file)[0] + "_rag_content.txt"
    output_file = args[1] if len(args) > 1 else default_output

    # Optional custom title
    title = args[2] if len(args) > 2 else None

    # Check if JS generation should be skipped
    generate_js = '--no-js-titles' not in flags

    if not os.path.exists(pdf_file):
        print(f"\n❌ Error: PDF file '{pdf_file}' not found\n")
        sys.exit(1)

    extract_pdf_for_rag(pdf_file, output_file, title, generate_js)
